main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

my_story_4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story_1.urls'))
]

story_1/urls.py
from django.urls import path

from . import views

app_name = "story_1"

urlpatterns = [
    path('story1/', views.story1, name='story1')
]

main/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'main/aboutme.html')

story_1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story_1/index.html')

main/templates/main/aboutme.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<title>Story 3</title>
{% endblock meta %}

{% block content %}
 <!-- LANDING PAGE -->
 <div id="home">
    <div class="d-flex flex-column top-cloud">
        <div class="top-cloud-1"></div>
        <div class="top-cloud-2"></div>
        <div class="top-cloud-3"></div>
    </div>

    <div class="d-flex justify-content-between middle">
        <div class="profile">
            <img src="{% static 'img/BIMA_2.png' %}" class="pic">
        </div>
        <div class="d-flex flex-column greet">
            <h1 class="block-hi">Hi,</h1>
            <h1><span class="inline-hi">Hi, </span>I'm <span class="first-name">Bima <span class="last-name">Bagas R</span></span></h1>
            <div class="sub-text">
                <p>Let's get to know me!</p>
            </div>
        </div>
    </div>

    <div class="d-flex flex-column align-items-end bottom-cloud">
        <div class="bottom-cloud-1"></div>
        <div class="bottom-cloud-2"></div>
    </div>
    <div class="d-flex flex-column align-items-center bottom-arrow">
        <div class="d-flex flex-column align-items-center ke-about">
            ABOUT ME
            <i class="fas fa-angle-down"></i>
        </div>
    </div>
</div>

<!-- ABOUT ME PAGE -->
<div id="about-me">
    <div class="d-flex flex-column top-cloud top-cloud-abme">
        <div class="top-cloud-1"></div>
        <div class="top-cloud-2"></div>
        <div class="top-cloud-3 minified"></div>
    </div>
    
    <div class="d-flex justify-content-between first-section">
        <div class="title">
            <h1>ABOUT</h1>
            <h1>ME</h1>
        </div>
        <div class="desc">
            <p>My name is Bima Bagas Raditya, a second year computer science student in Universitas Indonesia. Born in Jakarta, 10th of June 2001. Love to code and have big passion in mobile development.</p>
        </div>
    </div>

    <div class="ability">
        <div class="skills">
            <h1>SKILLS</h1>
            <div class="cont">
                <img src="{% static 'img/icons.svg' %}" alt="">
            </div>
        </div>
        <div class="experiences">
            <h1>EXPERIENCES</h1>
            <div class="exp">
                <div class="ppp">
                    <p class="job">Member of Mobile Development SIG</p>
                    <p class="com">RISTEK</p>
                    <p class="job">Staff of Fundraising</p>
                    <p class="com">COMPFEST 12</p>
                    <p class="job">Staff of Decoration</p>
                    <p class="com">PERAK FASILKOM</p>

                </div>
            </div>
        </div>
    </div>

    <div class="d-flex flex-column align-items-end bottom-cloud bottom-cloud-abme">
        <div class="bottom-cloud-1"></div>
        <div class="bottom-cloud-2"></div>
    </div>

    <div class="d-flex flex-row banner">
        <div class="ui">
            <img src="{% static 'img/ui_banner.svg' %}" alt="" class="ui-banner">
            <img src="{% static 'img/ui_logo.svg' %}" alt="" class="ui-logo">
        </div>
        <div class="smansa">
            <img src="{% static 'img/smansa_banner.svg' %}" alt="" class="smansa-banner">
            <img src="{% static 'img/logo_smansa.svg' %}" alt="" class="smansa-logo">
        </div>
    </div>
    <div class="d-flex flex-column align-items-center bottom-arrow">
            <i class="fas fa-angle-down ke-edu"></i>
    </div>
</div>

<!-- EDUCATION PAGE -->
<div id="edu">

    <div class="title">
      <h1>EDUCATION</h1>
    </div>
    
    <div class="schools">
      <div class="univ">
        <h2>Universitas Indonesia</h2>
        <h3>Computer Science, Faculty of Computer Science</h3>
        <h4>2019-now</h4>
      </div>
      <div class="sma">
        <h2>SMA Negeri 1 Bogor</h2>
        <h3>Natural Science</h3>
        <h4>2016-2019</h4>
      </div>
      <div class="smp">
        <h2>SMP Negeri 1 Bogor</h2>
        <h4>2013-2016</h3>
      </div>
      <div class="sd">
        <h2>SDN Sukadamai 3</h2>
        <h4>2007-2013</h4>
      </div>
    </div>
    
    <div class="d-flex flex-column align-items-end bottom-cloud">
      <div class="bottom-cloud-1"></div>
      <div class="bottom-cloud-2"></div>
  </div>
    <div class="d-flex flex-column align-items-center bottom-arrow">
        <i class="fas fa-angle-down ke-contact"></i>
    </div>

</div>
<!-- CONTACT ME PAGE -->
<div id="contact-me">
    <div class="d-flex flex-column justify-content-center isi">
        <div class="thankyou">
            <h1>Thank you for visiting my website!</h1>
            <span class="lb-text">get in touch with me in</span>
            <div class="d-flex flex-row justify-content-between align-items-center social">
                <a href="https://www.linkedin.com/in/bima-bagas-raditya-58830b16b/"><i class="fab fa-linkedin"></i></a>
                <a href="https://fb.com/bima.b.r.5">
                    <i class="fab fa-facebook"></i>
                </a>
                <a href="https://twitter.com/bbima4">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="https://instagram.com/bimabr">
                    <i class="fab fa-instagram"></i>
                </a>
            </div>
        </div>
        <span class="lb-text">or</span>
        <div class="email-me">
            <form>
                <div class="email-me-ct">
                    <input type="text" placeholder="Your email">
                </div>
                <div class="email-me-ct">
                    <textarea placeholder="Your message"></textarea>
                </div>
            </form>
            <button type="submit" class="btn send">SEND</button>
        </div>
        
    </div>

    <div class="d-flex flex-column align-items-center bottom-arrow flipped">
        <i class="fas fa-angle-up"></i>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

story_1/templates/story_1/index.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="{% static 'css/njay.css' %}">
<title>Story 1 PPW</title>
{% endblock meta %}

{% block content %}
<div class="header">
    <h1>My Profile</h1>
</div>
<div class="middle">
    <div class="center">
        <div class="avatar">
            <img src="{% static 'img/MY09.jpg' %}" alt="image">
        </div>

        <div class="content">
            <h1>Bima Bagas Raditya</h1>
            <h3>1906398585</h2>
            <h2>Universitas Indonesia'19</h2>
            <p>a computer science student who's trying to jump into mobile development.</p>
            <p>watching animal vids is my hobby, especially a cat</p>
        </div>

        <div class="social">
            <a href="http://fb.com/bima.b.r.5" >
                <i class="fab fa-facebook"></i>
            </a>
            <a href="https://instagram.com/bimabr">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="https://twitter.com/bbima4">
                <i class="fab fa-twitter"></i>
            </a>
        </div>
    </div>
</div>
<div class="empty"></div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{% static 'js/njay.js' %}"></script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/e76dc76644.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <header class="d-flex flex-row justify-content-end">
    <div class="center-nav">
      <nav>
        <a href="#about-me" class="nav-about">About Me</a>
        <a href="#edu" class="nav-edu">Education</a>
        <a href="#contact-me" class="nav-contact">Contact</a>
        <a href="{% url 'story_1:story1' %}" class="nav-story1">Story 1</a>
        <a href="{% url 'main:home' %}" class="nav-story3 none">Story 3</a>
      </nav>
    </div>
  </header>
</body>
{% block content %}
{% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>